# Generated by Django 5.0.6 on 2025-08-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='total_vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
