# Generated by Django 4.2.15 on 2025-09-11 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_total_vendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='productos/'),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de la imagen', max_length=100)),
                ('es_principal', models.BooleanField(default=False, help_text='Marcar como imagen principal')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Imagen del Producto',
                'verbose_name_plural': 'Imágenes del Producto',
                'ordering': ['orden', '-fecha_subida'],
            },
        ),
    ]
