# Generated by Django 4.2.15 on 2025-11-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_imagen_principal_imagenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talla',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='tienda.producto'),
        ),
    ]
